name: Build, Test, Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Run Tests
        run: npm test

      - name: Test Build
        run: npm run build

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore Build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
